### ISSUE TITLE
Python 3 information is outdated

### ISSUE THREAD

**Issue by telenieko** [lino-framework/book#41]
This page: [about python 3 support](https://lino.readthedocs.io/en/master/dev/py3.html) talks about 2016 goals, and py3 not being supported.

But the linked issue says it's Closed, and it appears python 3 is in fact supported

**Comment by lsaffre** [comment]
Yes, that page was simply obsolete. Thanks for reporting. I removed it (at least on http://www.lino-framework.org/dev ... not sure whether RTD is always up to date). We now run new sites under Python 3, but there are still production sites using Python 2. The test suites pass for Py3 (except sometimes... as right now... https://travis-ci.org/lino-framework) we don't yet have very strict rules as we are a small team.

**Comment by telenieko** [comment]
As a side note; One thing that disturbed me when discovering Lino earlier this week is the absence of a requirements / support specification (that is: python versions, windows support, etc).

That information is normally available on the README file (so it shows up in the github repo  page) or on the documentation home / first pages. But Atleast regarding python 3 support one has to go to the pypi classifiers to notice (or look at the setup.py).

Maybe a note could be added to the README of the lino repo stating the versions it's known to work (or tested against).

BTW, I'm glad I discovered Lino this week. Having some fun with it!
