### ISSUE TITLE
Extjs6 and OpenUI5 reference

### ISSUE THREAD

**Issue by cas--** [lino-framework/book#45]
After a discussion with Luc, I understand that the React framework is replacing the old ExtJS 3 UI. However there are still sections in the book discussing OpenUI5 and ExtJS6 
which I feel are misleading to new users of the Lino project.

Relevant pages
- https://www.lino-framework.org/dev/oui5.html
- https://www.lino-framework.org/dev/overview.html?#extjs-6-front-end

Therefore should all reference to OpenUI5 and ExtJS6 be removed from the documentation? And should this also apply to the demo project's code?

**Comment by lsaffre** [comment]
Thanks for the report! Indeed there were some clearly obsolete
statements about it. I am working on it along with some other optimizations.

Luc

**Comment by lsaffre** [comment]
Done. The pages still exist at the old URL, but start now with a note that they are obsolete, and they are no longer shown in the TOC. Also adapted the overview.
